import Head from 'next/head';
import React from 'react';
import Image from 'next/image';
import { Filters } from '../components/Filters/Filters';
import { Product } from '../components/Product/Product';
import useContentful from '../hooks/useContentful';
import styles from '../styles/Home.module.css';
import { ProductProps } from '../types/types';

export default function Home() {
  const { getProducts } = useContentful();
  const [products, setProducts] = React.useState<ProductProps[] | undefined>(undefined);
  const [filteredProducts, setFilteredProducts] = React.useState<ProductProps[] | undefined>(undefined);
  const [isActive, setIsActive] = React.useState('all');

  React.useEffect(() => {
    getProducts().then((res) => {
      setProducts(res);
      setFilteredProducts(res);
    })
    console.log('running')
  }, [])

  const filterProducts = (category: string) => {
    setIsActive(category);
    if (category === 'all') {
      return setFilteredProducts(products);
    }

    const filtering = products?.filter((product) => product.category[0] === category);
    setFilteredProducts(filtering);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Image src="/next.png" alt="Vercel Logo" width={30} height={30} />
      </header>
      <main className={styles.main}>
        <Filters products={products} filterProducts={filterProducts} isActive={isActive} />
        <section>
          {filteredProducts?.map((product) => <Product product={product} key={product.title} />)}
        </section>
      </main>
    </div>
  )
}
